# Generated by Django 5.0.2 on 2024-04-01 08:59

import FastFoodApp.profiles.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.PositiveIntegerField(help_text='Age requirement: 18 years and above.', validators=[FastFoodApp.profiles.validators.validate_age])),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
