# Generated by Django 5.0.2 on 2024-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pictures/profile_picture.png', null=True, upload_to='media/profile_pictures/'),
        ),
    ]
